# Generated by Django 4.0 on 2022-01-07 14:54

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motorcycle_name', models.CharField(max_length=200)),
                ('motorcycle_image', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='images')),
            ],
        ),
    ]
