# Generated by Django 4.0 on 2022-01-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motorcycle_name', models.CharField(max_length=200)),
                ('motorcycle_brand', models.CharField(max_length=200)),
                ('motorcycle_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
