# Generated by Django 4.0 on 2022-01-08 01:21

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motorcycle_name', models.CharField(max_length=200)),
                ('motorcycle_brand', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MotorcycleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorcycle_image', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='motorcycles')),
                ('motorcycle_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='motorcycles.motorcycle')),
            ],
        ),
        migrations.DeleteModel(
            name='Motorcycles',
        ),
    ]
