# Generated by Django 4.0 on 2022-01-09 19:03

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='motorcycle_image',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='images'),
        ),
    ]
