# Generated by Django 4.0 on 2022-01-08 02:03

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0002_motorcycle_motorcycleimage_delete_motorcycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycleimage',
            name='motorcycle_image',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='images'),
        ),
    ]
